"""Reproducible survival analyses for the oncology registry project.

Place this file at:
    src/analysis/survival_extensions.py

Run from the project root with:
    python src/analysis/survival_extensions.py

The script:
- explicitly filters quality_status == "valid";
- validates the event indicator against vital_status;
- fits a primary Cox model (age + overall stage + grade);
- fits an ER/PR-stratified sensitivity Cox model;
- exports category, convergence, PH, and sample-flow diagnostics;
- writes only relative project paths to the run manifest;
- produces a machine-readable commit-readiness checklist.
"""

from __future__ import annotations

from contextlib import redirect_stdout
from datetime import datetime, timezone
from pathlib import Path
import hashlib
import json
import platform
import re
import sys
import warnings

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import lifelines
import statsmodels
from lifelines import CoxPHFitter, KaplanMeierFitter
from lifelines.exceptions import ConvergenceWarning
from lifelines.plotting import add_at_risk_counts
from lifelines.statistics import (
    multivariate_logrank_test,
    pairwise_logrank_test,
    proportional_hazard_test,
)
from statsmodels.stats.multitest import multipletests


# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_VERSION = "2026-08-05-commit-candidate-v1"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "oncology_registry_validated.csv"
)

CASE_ID_COL = "case_id"
DURATION_COL = "survival_months"
EVENT_COL = "event"  # 1 = death observed; 0 = right-censored
VITAL_STATUS_COL = "vital_status"
STAGE_COL = "overall_stage"
GRADE_COL = "grade"
QUALITY_STATUS_COL = "quality_status"
VALID_QUALITY_VALUE = "valid"

STAGE_ORDER = ["IIA", "IIB", "IIIA", "IIIB", "IIIC"]
EXPECTED_GRADE_VALUES = [
    "Well differentiated; Grade I",
    "Moderately differentiated; Grade II",
    "Poorly differentiated; Grade III",
    "Undifferentiated; anaplastic; Grade IV",
]
EXPECTED_RECEPTOR_VALUES = ["Negative", "Positive"]

SELECTED_TIMES_MONTHS = [0, 12, 24, 36, 60, 84, 108]

# Main model retained after the previous PH review.
COX_NUMERIC_COLS = ["age"]
COX_CATEGORICAL_COLS = [STAGE_COL, GRADE_COL]
REFERENCE_CATEGORIES = {
    STAGE_COL: "IIA",
    GRADE_COL: "Moderately differentiated; Grade II",
}

# Sensitivity model: ER and PR define separate baseline hazards.
SENSITIVITY_STRATA_COLS = [
    "estrogen_status",
    "progesterone_status",
]

COX_PENALIZER = 0.0
MIN_RECOMMENDED_GROUP_SIZE = 20
MIN_RECOMMENDED_EVENTS = 5
MIN_EVENTS_PER_PARAMETER_WARNING = 10.0

# False means that lifelines displays end-of-period at-risk counts.
AT_RISK_COUNT_FROM_START_OF_PERIOD = False

FIGURE_DIR = PROJECT_ROOT / "outputs" / "figures" / "survival"
REPORT_DIR = PROJECT_ROOT / "outputs" / "reports" / "survival"


# =============================================================================
# UTILITIES
# =============================================================================


def fail(message: str) -> None:
    """Stop with a readable error and a non-zero exit status."""
    raise SystemExit(f"\nERROR: {message}\n")


def show_available_columns(df: pd.DataFrame) -> str:
    """Return available columns in a readable form."""
    return "\n".join(f"  - {column}" for column in df.columns)


def sha256_file(path: Path) -> str:
    """Calculate a SHA-256 digest without loading the whole file into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def project_relative_path(path: Path) -> str:
    """Return a portable project-relative path, never a local absolute path."""
    try:
        return path.resolve().relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return path.name


def json_text(value: object) -> str:
    """Serialize lists and dictionaries in a portable, unambiguous format."""
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def sanitize_filename(text: str, maximum_length: int = 90) -> str:
    """Create a safe filename fragment from a figure title."""
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", text.strip())
    cleaned = cleaned.strip("._-")
    return (cleaned[:maximum_length] or "diagnostic").lower()


def clean_previous_outputs() -> None:
    """Remove only outputs generated by this survival-analysis workflow."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    report_patterns = [
        "quality_*.csv",
        "case_id_validation.csv",
        "vital_status_event_crosstab.csv",
        "survival_exclusion_report.csv",
        "survival_sample_flow.csv",
        "event_censor_summary_*.csv",
        "at_risk_counts_selected_times.csv",
        "logrank_*.csv",
        "cox_primary_*",
        "cox_stratified_*",
        "cox_primary_vs_stratified_sensitivity.csv",
        "survival_analysis_run_manifest.csv",
        "commit_readiness_checklist.csv",
        # Legacy names from earlier runs.
        "cox_missingness_by_column*.csv",
        "cox_model_*.csv",
        "cox_model_*.txt",
        "cox_proportional_hazards_test*.csv",
        "cox_sample_flow*.csv",
        "cox_check_assumptions_report.txt",
    ]
    figure_patterns = [
        "overall_survival_with_censoring_and_risk_table.png",
        "survival_by_stage_with_censoring_and_risk_table.png",
        "cox_primary_*.png",
        "cox_stratified_*.png",
        # Legacy names from earlier runs.
        "cox_adjusted_hazard_ratios*.png",
        "cox_schoenfeld_diagnostic_*.png",
    ]

    for pattern in report_patterns:
        for path in REPORT_DIR.glob(pattern):
            if path.is_file():
                path.unlink()

    for pattern in figure_patterns:
        for path in FIGURE_DIR.glob(pattern):
            if path.is_file():
                path.unlink()


def load_dataset(path: Path) -> pd.DataFrame:
    """Load the processed CSV used by this project."""
    if not path.exists():
        fail(
            f"Data file not found: {path}\n"
            "Expected: data/processed/oncology_registry_validated.csv"
        )
    if path.suffix.lower() != ".csv":
        fail("This project configuration expects a CSV file.")
    try:
        return pd.read_csv(path, encoding="utf-8")
    except Exception as exc:
        fail(f"Could not read the CSV: {type(exc).__name__}: {exc}")
    return pd.DataFrame()  # Unreachable.


def validate_required_schema(df: pd.DataFrame) -> None:
    """Validate columns required across all descriptive and Cox analyses."""
    required = [
        CASE_ID_COL,
        "age",
        STAGE_COL,
        GRADE_COL,
        "estrogen_status",
        "progesterone_status",
        DURATION_COL,
        VITAL_STATUS_COL,
        EVENT_COL,
        QUALITY_STATUS_COL,
    ]
    missing = [column for column in required if column not in df.columns]
    if missing:
        fail(
            f"Required project columns are missing: {missing}.\n"
            f"Available columns:\n{show_available_columns(df)}"
        )

    duplicate_column_names = df.columns[df.columns.duplicated()].tolist()
    if duplicate_column_names:
        fail(f"Duplicate column names detected: {duplicate_column_names}")


def validate_case_ids(df: pd.DataFrame) -> None:
    """Require non-missing and unique technical case identifiers."""
    series = df[CASE_ID_COL].astype("string").str.strip()
    n_missing = int(series.isna().sum() + series.eq("").sum())
    n_duplicated = int(series[series.notna() & series.ne("")].duplicated().sum())

    pd.DataFrame(
        [
            {"metric": "n_records", "value": int(len(df))},
            {"metric": "missing_or_blank_case_id", "value": n_missing},
            {"metric": "duplicated_case_id", "value": n_duplicated},
        ]
    ).to_csv(REPORT_DIR / "case_id_validation.csv", index=False)

    if n_missing:
        fail(f"{n_missing} record(s) have a missing or blank {CASE_ID_COL!r}.")
    if n_duplicated:
        fail(f"{n_duplicated} duplicated {CASE_ID_COL!r} value(s) were detected.")


def normalize_text(series: pd.Series) -> pd.Series:
    """Trim categorical labels while preserving missing values."""
    return series.astype("string").str.strip()


def validate_expected_categories(
    df: pd.DataFrame,
    column: str,
    expected_values: list[str],
) -> None:
    """Stop on unexpected non-missing category labels."""
    observed = sorted(str(value) for value in normalize_text(df[column]).dropna().unique())
    unexpected = sorted(set(observed).difference(expected_values))
    if unexpected:
        fail(
            f"Unexpected categories in {column!r}: {unexpected}.\n"
            f"Expected categories: {expected_values}"
        )


# =============================================================================
# QUALITY FILTER, EVENT VALIDATION, AND SAMPLE FLOW
# =============================================================================


def filter_valid_quality_records(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, int]:
    """Explicitly retain only quality_status == 'valid' and document the filter."""
    normalized = normalize_text(df[QUALITY_STATUS_COL]).str.lower()
    display_values = normalized.fillna("<missing>")

    distribution = (
        display_values.value_counts(dropna=False)
        .rename_axis(QUALITY_STATUS_COL)
        .reset_index(name="n_records")
    )
    distribution["percent"] = 100 * distribution["n_records"] / len(df)
    distribution.to_csv(
        REPORT_DIR / "quality_status_distribution.csv",
        index=False,
    )

    valid_mask = normalized.eq(VALID_QUALITY_VALUE).fillna(False)
    filtered = df.loc[valid_mask].copy()
    excluded = int((~valid_mask).sum())

    pd.DataFrame(
        [
            {"metric": "source_records", "value": int(len(df))},
            {"metric": "quality_valid_records", "value": int(valid_mask.sum())},
            {
                "metric": "excluded_nonvalid_or_missing_quality_status",
                "value": excluded,
            },
            {
                "metric": "quality_filter",
                "value": f"{QUALITY_STATUS_COL} == {VALID_QUALITY_VALUE!r}",
            },
        ]
    ).to_csv(REPORT_DIR / "quality_filter_summary.csv", index=False)

    if filtered.empty:
        fail("No records remain after the explicit quality-status filter.")

    print(
        f"Quality filter: retained {len(filtered)} of {len(df)} records "
        f"where {QUALITY_STATUS_COL} == {VALID_QUALITY_VALUE!r}."
    )
    return filtered, excluded


def validate_event_indicator(df: pd.DataFrame) -> pd.DataFrame:
    """Validate event and cross-check every recognized vital-status value."""
    result = df.copy()
    original_event = result[EVENT_COL]
    numeric_event = pd.to_numeric(original_event, errors="coerce")

    invalid_nonmissing = original_event.notna() & numeric_event.isna()
    if invalid_nonmissing.any():
        examples = original_event.loc[invalid_nonmissing].astype(str).unique()[:10]
        fail(
            f"{EVENT_COL!r} contains non-numeric values: {examples.tolist()}. "
            "Only 0 and 1 are permitted."
        )

    result[EVENT_COL] = numeric_event
    nonmissing_values = set(result[EVENT_COL].dropna().unique())
    if not nonmissing_values.issubset({0, 1, 0.0, 1.0}):
        fail(
            f"{EVENT_COL!r} contains values other than 0 and 1: "
            f"{sorted(nonmissing_values)}"
        )

    vital = normalize_text(result[VITAL_STATUS_COL]).str.lower()
    mapping = {"alive": 0, "dead": 1}

    unknown_vital = vital.notna() & ~vital.isin(mapping)
    if unknown_vital.any():
        examples = result.loc[unknown_vital, VITAL_STATUS_COL].astype(str).unique()[:10]
        fail(
            f"Unrecognized values in {VITAL_STATUS_COL!r}: {examples.tolist()}. "
            "Expected only 'Alive' and 'Dead'."
        )

    expected_event = vital.map(mapping)
    comparable = expected_event.notna() & result[EVENT_COL].notna()
    inconsistent = comparable & expected_event.ne(result[EVENT_COL])
    if inconsistent.any():
        fail(
            f"Detected {int(inconsistent.sum())} inconsistencies between "
            f"{VITAL_STATUS_COL!r} and {EVENT_COL!r}."
        )

    pd.crosstab(
        result[VITAL_STATUS_COL],
        result[EVENT_COL],
        dropna=False,
    ).to_csv(REPORT_DIR / "vital_status_event_crosstab.csv")

    return result


def prepare_survival_data(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, int]:
    """Validate core survival fields within the quality-valid cohort."""
    working = df.copy()
    working[DURATION_COL] = pd.to_numeric(
        working[DURATION_COL],
        errors="coerce",
    )
    working[EVENT_COL] = pd.to_numeric(
        working[EVENT_COL],
        errors="coerce",
    )
    working[STAGE_COL] = normalize_text(working[STAGE_COL])

    flags = pd.DataFrame(index=working.index)
    flags["missing_duration"] = working[DURATION_COL].isna()
    flags["negative_duration"] = working[DURATION_COL].lt(0).fillna(False)
    flags["missing_event"] = working[EVENT_COL].isna()
    flags["invalid_event"] = (
        working[EVENT_COL].notna()
        & ~working[EVENT_COL].isin([0, 1])
    )
    flags["missing_stage"] = (
        working[STAGE_COL].isna()
        | working[STAGE_COL].eq("")
    )
    flags["exclude_from_core_survival"] = flags.any(axis=1)

    report = pd.DataFrame(
        {
            "criterion": flags.columns,
            "n_records": [
                int(flags[column].sum())
                for column in flags.columns
            ],
            "scope": "quality-valid records",
        }
    )

    excluded_core = int(flags["exclude_from_core_survival"].sum())
    clean = working.loc[
        ~flags["exclude_from_core_survival"]
    ].copy()
    clean[EVENT_COL] = clean[EVENT_COL].astype(int)

    if clean.empty:
        fail("No valid records remain for survival analysis.")
    if int(clean[EVENT_COL].sum()) == 0:
        fail("No observed deaths remain; survival models are not estimable.")
    if int(clean[EVENT_COL].sum()) == len(clean):
        print("WARNING: no censored records remain in the core survival cohort.")

    return clean, report, excluded_core


def write_survival_flow_reports(
    source_n: int,
    quality_valid_n: int,
    quality_excluded_n: int,
    core_survival_df: pd.DataFrame,
    core_excluded_n: int,
    core_report: pd.DataFrame,
) -> None:
    """Write a unified, sequential accounting of all exclusions."""
    combined_exclusion_report = pd.concat(
        [
            pd.DataFrame(
                [
                    {
                        "criterion": "nonvalid_or_missing_quality_status",
                        "n_records": quality_excluded_n,
                        "scope": "source records",
                    }
                ]
            ),
            core_report,
        ],
        ignore_index=True,
    )
    combined_exclusion_report.to_csv(
        REPORT_DIR / "survival_exclusion_report.csv",
        index=False,
    )

    events = int(core_survival_df[EVENT_COL].sum())
    censored = int(len(core_survival_df) - events)
    pd.DataFrame(
        [
            {"step": "source_records", "n_records": source_n},
            {
                "step": "quality_valid_records",
                "n_records": quality_valid_n,
            },
            {
                "step": "excluded_nonvalid_or_missing_quality_status",
                "n_records": quality_excluded_n,
            },
            {
                "step": "excluded_for_core_survival_fields",
                "n_records": core_excluded_n,
            },
            {
                "step": "final_core_survival_records",
                "n_records": int(len(core_survival_df)),
            },
            {"step": "observed_deaths", "n_records": events},
            {"step": "right_censored", "n_records": censored},
        ]
    ).to_csv(REPORT_DIR / "survival_sample_flow.csv", index=False)


# =============================================================================
# DESCRIPTIVE SURVIVAL OUTPUTS
# =============================================================================


def ordered_stage_values(series: pd.Series) -> list[str]:
    """Return stage labels in their configured clinical order."""
    observed = [str(value) for value in series.dropna().unique()]
    configured = [
        stage for stage in STAGE_ORDER
        if stage in observed
    ]
    remaining = sorted(
        stage for stage in observed
        if stage not in configured
    )
    return configured + remaining


def selected_times_within_followup(
    df: pd.DataFrame,
) -> list[int]:
    """Keep configured times within the observed follow-up range."""
    maximum = float(df[DURATION_COL].max())
    times = sorted(
        {
            int(time)
            for time in SELECTED_TIMES_MONTHS
            if 0 <= time <= maximum
        }
    )
    if 0 not in times:
        times.insert(0, 0)
    return times


def save_event_and_censor_summaries(
    df: pd.DataFrame,
) -> None:
    """Export overall and stage-specific event/censor counts."""
    n_total = int(len(df))
    n_events = int(df[EVENT_COL].sum())
    n_censored = n_total - n_events

    pd.DataFrame(
        [
            {
                "n_total": n_total,
                "n_events": n_events,
                "n_censored": n_censored,
                "event_percent": 100 * n_events / n_total,
                "censored_percent": 100 * n_censored / n_total,
                "minimum_followup_months": float(
                    df[DURATION_COL].min()
                ),
                "maximum_followup_months": float(
                    df[DURATION_COL].max()
                ),
            }
        ]
    ).to_csv(
        REPORT_DIR / "event_censor_summary_overall.csv",
        index=False,
    )

    by_stage = (
        df.groupby(STAGE_COL, observed=True)
        .agg(
            n_total=(EVENT_COL, "size"),
            n_events=(EVENT_COL, "sum"),
            minimum_followup_months=(DURATION_COL, "min"),
            maximum_followup_months=(DURATION_COL, "max"),
        )
        .reset_index()
    )
    by_stage["n_events"] = by_stage["n_events"].astype(int)
    by_stage["n_censored"] = (
        by_stage["n_total"] - by_stage["n_events"]
    )
    by_stage["event_percent"] = (
        100 * by_stage["n_events"] / by_stage["n_total"]
    )
    by_stage["censored_percent"] = (
        100 * by_stage["n_censored"] / by_stage["n_total"]
    )

    stage_rank = {
        stage: rank
        for rank, stage in enumerate(
            ordered_stage_values(df[STAGE_COL])
        )
    }
    by_stage["_stage_rank"] = by_stage[STAGE_COL].map(stage_rank)
    by_stage = (
        by_stage.sort_values("_stage_rank")
        .drop(columns="_stage_rank")
    )
    by_stage.to_csv(
        REPORT_DIR / "event_censor_summary_by_stage.csv",
        index=False,
    )


def create_at_risk_table(
    df: pd.DataFrame,
    times: list[int],
) -> None:
    """Export end-of-period risk counts matching the lifelines plot convention."""
    rows: list[dict[str, object]] = []

    groups: list[tuple[str, pd.DataFrame]] = [
        ("Overall", df)
    ]
    groups.extend(
        (
            stage,
            df.loc[df[STAGE_COL] == stage],
        )
        for stage in ordered_stage_values(df[STAGE_COL])
    )

    for label, group in groups:
        for time in times:
            rows.append(
                {
                    "group": label,
                    "time_months": time,
                    "n_at_risk_end_of_period": int(
                        (group[DURATION_COL] > time).sum()
                    ),
                    "cumulative_events_through_time": int(
                        (
                            (group[DURATION_COL] <= time)
                            & group[EVENT_COL].eq(1)
                        ).sum()
                    ),
                    "cumulative_censored_through_time": int(
                        (
                            (group[DURATION_COL] <= time)
                            & group[EVENT_COL].eq(0)
                        ).sum()
                    ),
                }
            )

    pd.DataFrame(rows).to_csv(
        REPORT_DIR / "at_risk_counts_selected_times.csv",
        index=False,
    )


def plot_kaplan_meier(
    df: pd.DataFrame,
    times: list[int],
) -> None:
    """Create overall and stage-specific Kaplan–Meier figures."""
    overall = KaplanMeierFitter(label="Analytical cohort")
    overall.fit(
        df[DURATION_COL],
        event_observed=df[EVENT_COL],
    )

    fig, ax = plt.subplots(figsize=(12, 8))
    overall.plot_survival_function(
        ax=ax,
        ci_show=True,
        show_censors=True,
        censor_styles={
            "marker": "|",
            "ms": 7,
            "mew": 1.2,
        },
    )
    add_at_risk_counts(
        overall,
        ax=ax,
        xticks=times,
        rows_to_show=["At risk", "Censored", "Events"],
        at_risk_count_from_start_of_period=(
            AT_RISK_COUNT_FROM_START_OF_PERIOD
        ),
    )
    ax.set_title("Overall Kaplan–Meier survival estimate")
    ax.set_xlabel("Follow-up duration (months)")
    ax.set_ylabel("Estimated survival probability")
    ax.set_ylim(0, 1.02)
    ax.grid(alpha=0.2)
    fig.subplots_adjust(bottom=0.30)
    fig.savefig(
        FIGURE_DIR
        / "overall_survival_with_censoring_and_risk_table.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(13, 9))
    fitters: list[KaplanMeierFitter] = []
    for stage in ordered_stage_values(df[STAGE_COL]):
        subset = df.loc[df[STAGE_COL] == stage]
        kmf = KaplanMeierFitter(label=stage)
        kmf.fit(
            subset[DURATION_COL],
            event_observed=subset[EVENT_COL],
        )
        kmf.plot_survival_function(
            ax=ax,
            ci_show=True,
            show_censors=True,
            censor_styles={
                "marker": "|",
                "ms": 5,
                "mew": 1.0,
            },
        )
        fitters.append(kmf)

    add_at_risk_counts(
        *fitters,
        ax=ax,
        xticks=times,
        rows_to_show=["At risk"],
        at_risk_count_from_start_of_period=(
            AT_RISK_COUNT_FROM_START_OF_PERIOD
        ),
    )
    ax.set_title(
        "Kaplan–Meier survival estimates by recorded stage"
    )
    ax.set_xlabel("Follow-up duration (months)")
    ax.set_ylabel("Estimated survival probability")
    ax.set_ylim(0, 1.02)
    ax.grid(alpha=0.2)
    fig.subplots_adjust(bottom=0.30)
    fig.savefig(
        FIGURE_DIR
        / "survival_by_stage_with_censoring_and_risk_table.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close(fig)


def run_logrank_tests(df: pd.DataFrame) -> None:
    """Run global and Holm-adjusted pairwise log-rank tests."""
    global_result = multivariate_logrank_test(
        event_durations=df[DURATION_COL],
        groups=df[STAGE_COL],
        event_observed=df[EVENT_COL],
    )
    global_summary = (
        global_result.summary.reset_index(drop=True)
    )
    global_summary.insert(
        0,
        "test",
        "global_multivariate_logrank",
    )
    global_summary.insert(
        1,
        "number_of_groups",
        df[STAGE_COL].nunique(),
    )
    global_summary.to_csv(
        REPORT_DIR / "logrank_global.csv",
        index=False,
    )

    pairwise = pairwise_logrank_test(
        event_durations=df[DURATION_COL],
        groups=df[STAGE_COL],
        event_observed=df[EVENT_COL],
    ).summary.reset_index()

    first_two = pairwise.columns[:2].tolist()
    pairwise = pairwise.rename(
        columns={
            first_two[0]: "group_1",
            first_two[1]: "group_2",
        }
    )
    reject, adjusted, _, _ = multipletests(
        pairwise["p"].to_numpy(),
        alpha=0.05,
        method="holm",
    )
    pairwise["p_holm"] = adjusted
    pairwise["reject_h0_after_holm"] = reject
    pairwise.to_csv(
        REPORT_DIR / "logrank_pairwise_holm.csv",
        index=False,
    )


# =============================================================================
# COX DATA PREPARATION AND DIAGNOSTICS
# =============================================================================


def apply_reference_categories(
    df: pd.DataFrame,
    categorical_cols: list[str],
) -> pd.DataFrame:
    """Apply every categorical reference explicitly before dummy encoding."""
    result = df.copy()

    missing_references = [
        column
        for column in categorical_cols
        if column not in REFERENCE_CATEGORIES
    ]
    if missing_references:
        fail(
            "Explicit reference categories are missing for: "
            f"{missing_references}"
        )

    for column in categorical_cols:
        result[column] = normalize_text(result[column])
        reference = REFERENCE_CATEGORIES[column]
        observed = sorted(
            str(value)
            for value in result[column].dropna().unique()
        )
        if reference not in observed:
            fail(
                f"Reference category {reference!r} was not found "
                f"in {column!r}. Observed categories: {observed}"
            )
        categories = [
            reference,
            *[
                value
                for value in observed
                if value != reference
            ],
        ]
        result[column] = pd.Categorical(
            result[column],
            categories=categories,
        )

    return result


def export_level_diagnostics(
    complete_raw: pd.DataFrame,
    variables: list[str],
    prefix: str,
    strata_cols: list[str] | None = None,
) -> pd.DataFrame:
    """Export counts, events, censoring, and sparse-cell warnings by level."""
    strata_cols = strata_cols or []
    rows: list[dict[str, object]] = []

    for variable in variables:
        for level, group in complete_raw.groupby(
            variable,
            observed=True,
            dropna=False,
        ):
            n_total = int(len(group))
            n_events = int(group[EVENT_COL].sum())
            rows.append(
                {
                    "variable": variable,
                    "level": str(level),
                    "role": (
                        "stratum"
                        if variable in strata_cols
                        else "covariate"
                    ),
                    "is_reference": bool(
                        variable in REFERENCE_CATEGORIES
                        and str(level)
                        == REFERENCE_CATEGORIES[variable]
                    ),
                    "n_total": n_total,
                    "n_events": n_events,
                    "n_censored": n_total - n_events,
                    "event_percent": (
                        100 * n_events / n_total
                        if n_total
                        else np.nan
                    ),
                    "sparse_n_warning": (
                        n_total
                        < MIN_RECOMMENDED_GROUP_SIZE
                    ),
                    "sparse_event_warning": (
                        n_events
                        < MIN_RECOMMENDED_EVENTS
                    ),
                }
            )

    diagnostics = pd.DataFrame(rows)
    diagnostics.to_csv(
        REPORT_DIR
        / f"{prefix}_categorical_level_diagnostics.csv",
        index=False,
    )
    return diagnostics


def export_combined_strata_diagnostics(
    complete_raw: pd.DataFrame,
    strata_cols: list[str],
    prefix: str,
) -> pd.DataFrame:
    """Report the actual combined strata used by the stratified Cox model."""
    if not strata_cols:
        return pd.DataFrame()

    combined = (
        complete_raw.groupby(
            strata_cols,
            observed=True,
            dropna=False,
        )
        .agg(
            n_total=(EVENT_COL, "size"),
            n_events=(EVENT_COL, "sum"),
        )
        .reset_index()
    )
    combined["n_events"] = combined["n_events"].astype(int)
    combined["n_censored"] = (
        combined["n_total"] - combined["n_events"]
    )
    combined["event_percent"] = (
        100 * combined["n_events"] / combined["n_total"]
    )
    combined["sparse_n_warning"] = (
        combined["n_total"] < MIN_RECOMMENDED_GROUP_SIZE
    )
    combined["sparse_event_warning"] = (
        combined["n_events"] < MIN_RECOMMENDED_EVENTS
    )
    combined["zero_event_blocker"] = combined["n_events"].eq(0)

    combined.to_csv(
        REPORT_DIR
        / f"{prefix}_combined_strata_diagnostics.csv",
        index=False,
    )

    if combined["zero_event_blocker"].any():
        problematic = combined.loc[
            combined["zero_event_blocker"],
            strata_cols,
        ].to_dict(orient="records")
        fail(
            "At least one ER/PR stratum has zero observed deaths: "
            f"{problematic}. The stratified sensitivity model is not "
            "adequately supported without further methodological review."
        )

    return combined


def prepare_cox_dataset(
    df: pd.DataFrame,
    prefix: str,
    strata_cols: list[str] | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Create a complete-case, reference-controlled Cox dataset."""
    strata_cols = strata_cols or []

    configured_columns = (
        COX_NUMERIC_COLS
        + COX_CATEGORICAL_COLS
        + strata_cols
    )
    duplicates = sorted(
        {
            column
            for column in configured_columns
            if configured_columns.count(column) > 1
        }
    )
    if duplicates:
        fail(
            f"Columns configured more than once in {prefix}: "
            f"{duplicates}"
        )

    all_columns = [
        DURATION_COL,
        EVENT_COL,
        *configured_columns,
    ]
    missing = [
        column
        for column in all_columns
        if column not in df.columns
    ]
    if missing:
        fail(
            f"Configured Cox columns are missing: {missing}.\n"
            f"Available columns:\n{show_available_columns(df)}"
        )

    raw = df[all_columns].copy()
    raw[DURATION_COL] = pd.to_numeric(
        raw[DURATION_COL],
        errors="coerce",
    )
    raw[EVENT_COL] = pd.to_numeric(
        raw[EVENT_COL],
        errors="coerce",
    )

    for column in COX_NUMERIC_COLS:
        raw[column] = pd.to_numeric(
            raw[column],
            errors="coerce",
        )

    raw = apply_reference_categories(
        raw,
        COX_CATEGORICAL_COLS,
    )

    for column in strata_cols:
        raw[column] = normalize_text(raw[column])

    missingness = (
        raw.isna()
        .sum()
        .rename("n_missing")
        .reset_index()
        .rename(columns={"index": "column"})
    )
    missingness.to_csv(
        REPORT_DIR / f"{prefix}_missingness_by_column.csv",
        index=False,
    )

    before = int(len(raw))
    complete_raw = raw.dropna().copy()
    after = int(len(complete_raw))
    if complete_raw.empty:
        fail(f"No complete cases remain for {prefix}.")

    # Use ordinary Python strings for strata labels after missingness removal.
    for column in strata_cols:
        complete_raw[column] = complete_raw[column].astype(str)

    level_diagnostics = export_level_diagnostics(
        complete_raw,
        [
            *COX_CATEGORICAL_COLS,
            *strata_cols,
        ],
        prefix,
        strata_cols,
    )
    export_combined_strata_diagnostics(
        complete_raw,
        strata_cols,
        prefix,
    )

    encoded = pd.get_dummies(
        complete_raw,
        columns=COX_CATEGORICAL_COLS,
        drop_first=True,
        dtype=int,
    )

    covariate_columns = [
        column
        for column in encoded.columns
        if column not in {
            DURATION_COL,
            EVENT_COL,
            *strata_cols,
        }
    ]
    constants = [
        column
        for column in covariate_columns
        if encoded[column].nunique() <= 1
    ]
    if constants:
        fail(
            f"Constant covariates in {prefix}: {constants}"
        )

    n_events = int(encoded[EVENT_COL].sum())
    n_parameters = int(len(covariate_columns))
    if n_events == 0:
        fail(f"No events remain in the complete-case sample for {prefix}.")
    if n_parameters == 0:
        fail(f"No estimable parameters remain for {prefix}.")

    events_per_parameter = n_events / n_parameters
    sample_flow = pd.DataFrame(
        [
            {
                "metric": "core_survival_records",
                "value": before,
            },
            {
                "metric": "cox_complete_cases",
                "value": after,
            },
            {
                "metric": "cox_records_excluded_for_missingness",
                "value": before - after,
            },
            {
                "metric": "cox_observed_events",
                "value": n_events,
            },
            {
                "metric": "cox_estimated_parameters",
                "value": n_parameters,
            },
            {
                "metric": "events_per_estimated_parameter_descriptive",
                "value": events_per_parameter,
            },
            {
                "metric": "events_per_parameter_warning_below",
                "value": MIN_EVENTS_PER_PARAMETER_WARNING,
            },
            {
                "metric": "events_per_parameter_warning",
                "value": (
                    events_per_parameter
                    < MIN_EVENTS_PER_PARAMETER_WARNING
                ),
            },
        ]
    )
    sample_flow.to_csv(
        REPORT_DIR / f"{prefix}_sample_flow.csv",
        index=False,
    )

    pd.DataFrame(
        [
            {
                "variable": variable,
                "reference_category": reference,
            }
            for variable, reference
            in REFERENCE_CATEGORIES.items()
            if variable in COX_CATEGORICAL_COLS
        ]
    ).to_csv(
        REPORT_DIR / f"{prefix}_reference_categories.csv",
        index=False,
    )

    return encoded, level_diagnostics, sample_flow


def fit_cox_model(
    cox_df: pd.DataFrame,
    prefix: str,
    title: str,
    strata_cols: list[str] | None = None,
) -> tuple[CoxPHFitter, pd.DataFrame]:
    """Fit Cox model, capture warnings, and reject unstable numerical output."""
    strata_cols = strata_cols or []
    cph = CoxPHFitter(penalizer=COX_PENALIZER)

    caught_warnings: list[warnings.WarningMessage]
    try:
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            cph.fit(
                cox_df,
                duration_col=DURATION_COL,
                event_col=EVENT_COL,
                strata=strata_cols or None,
                show_progress=False,
            )
        caught_warnings = list(caught)
    except Exception as exc:
        fail(
            f"{prefix} did not converge or could not be fitted.\n"
            f"{type(exc).__name__}: {exc}\n"
            "Review sparse categories, correlated variables, and coding."
        )

    warning_rows = [
        {
            "category": item.category.__name__,
            "message": str(item.message),
        }
        for item in caught_warnings
    ]
    warnings_df = pd.DataFrame(
        warning_rows,
        columns=["category", "message"],
    )
    warnings_df.to_csv(
        REPORT_DIR / f"{prefix}_fit_warnings.csv",
        index=False,
    )

    convergence_warning_messages = [
        str(item.message)
        for item in caught_warnings
        if issubclass(item.category, ConvergenceWarning)
    ]
    if convergence_warning_messages:
        fail(
            f"{prefix} emitted ConvergenceWarning:\n- "
            + "\n- ".join(convergence_warning_messages)
        )

    summary = (
        cph.summary.reset_index()
        .rename(columns={cph.summary.index.name or "index": "term"})
    )
    if "term" not in summary.columns:
        summary = summary.rename(
            columns={summary.columns[0]: "term"}
        )

    numeric_columns_to_check = [
        column
        for column in [
            "coef",
            "exp(coef)",
            "se(coef)",
            "coef lower 95%",
            "coef upper 95%",
            "exp(coef) lower 95%",
            "exp(coef) upper 95%",
            "p",
        ]
        if column in summary.columns
    ]
    finite_values = np.isfinite(
        summary[numeric_columns_to_check]
        .to_numpy(dtype=float)
    ).all()
    if not finite_values:
        fail(
            f"{prefix} produced non-finite coefficients, standard errors, "
            "confidence limits, or p-values."
        )

    summary.to_csv(
        REPORT_DIR / f"{prefix}_model_summary.csv",
        index=False,
    )

    with (
        REPORT_DIR / f"{prefix}_model_console_summary.txt"
    ).open("w", encoding="utf-8") as handle:
        with redirect_stdout(handle):
            cph.print_summary(decimals=4)

    pd.DataFrame(
        [
            {
                "metric": "concordance_index",
                "value": cph.concordance_index_,
            },
            {
                "metric": "log_likelihood",
                "value": cph.log_likelihood_,
            },
            {
                "metric": "partial_AIC",
                "value": cph.AIC_partial_,
            },
            {
                "metric": "n_observations",
                "value": int(len(cox_df)),
            },
            {
                "metric": "n_events",
                "value": int(cox_df[EVENT_COL].sum()),
            },
            {
                "metric": "strata",
                "value": json_text(strata_cols),
            },
            {
                "metric": "convergence_warning_count",
                "value": len(convergence_warning_messages),
            },
        ]
    ).to_csv(
        REPORT_DIR / f"{prefix}_model_metrics.csv",
        index=False,
    )

    fig, ax = plt.subplots(
        figsize=(
            10,
            max(5, 0.55 * len(summary) + 2),
        )
    )
    cph.plot(ax=ax, hazard_ratios=True)
    ax.set_title(title)
    ax.set_xlabel(
        "Hazard ratio with 95% confidence interval"
    )
    ax.axvline(1.0, linestyle="--", linewidth=1)
    fig.tight_layout()
    fig.savefig(
        FIGURE_DIR
        / f"{prefix}_adjusted_hazard_ratios.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close(fig)

    return cph, warnings_df


def check_proportional_hazards(
    cph: CoxPHFitter,
    cox_df: pd.DataFrame,
    prefix: str,
) -> pd.DataFrame:
    """Export Holm-adjusted PH tests, text advice, and Schoenfeld plots."""
    try:
        result = proportional_hazard_test(
            cph,
            cox_df,
            time_transform="rank",
        )
    except Exception as exc:
        fail(
            f"Could not run the PH test for {prefix}: "
            f"{type(exc).__name__}: {exc}"
        )

    summary = (
        result.summary.reset_index()
        .rename(columns={result.summary.index.name or "index": "term"})
    )
    if "term" not in summary.columns:
        summary = summary.rename(
            columns={summary.columns[0]: "term"}
        )

    reject, adjusted, _, _ = multipletests(
        summary["p"].to_numpy(),
        alpha=0.05,
        method="holm",
    )
    summary["p_holm"] = adjusted
    summary["reject_ph_after_holm"] = reject
    summary.to_csv(
        REPORT_DIR
        / f"{prefix}_proportional_hazards_test.csv",
        index=False,
    )

    plt.close("all")
    report_path = (
        REPORT_DIR
        / f"{prefix}_check_assumptions_report.txt"
    )
    try:
        with report_path.open(
            "w",
            encoding="utf-8",
        ) as handle:
            with redirect_stdout(handle):
                cph.check_assumptions(
                    cox_df,
                    p_value_threshold=0.05,
                    show_plots=True,
                )
    except Exception as exc:
        plt.close("all")
        fail(
            f"Could not run check_assumptions for {prefix}: "
            f"{type(exc).__name__}: {exc}"
        )

    figure_index_rows: list[dict[str, object]] = []
    for position, number in enumerate(
        plt.get_fignums(),
        start=1,
    ):
        figure = plt.figure(number)
        title = ""
        if figure._suptitle is not None:
            title = figure._suptitle.get_text()
        if not title and figure.axes:
            title = figure.axes[0].get_title()
        filename = (
            f"{prefix}_schoenfeld_diagnostic_"
            f"{position:02d}_{sanitize_filename(title)}.png"
        )
        figure.savefig(
            FIGURE_DIR / filename,
            dpi=300,
            bbox_inches="tight",
        )
        figure_index_rows.append(
            {
                "position": position,
                "filename": filename,
                "figure_title": title,
            }
        )
    plt.close("all")

    pd.DataFrame(
        figure_index_rows,
        columns=[
            "position",
            "filename",
            "figure_title",
        ],
    ).to_csv(
        REPORT_DIR
        / f"{prefix}_schoenfeld_figure_index.csv",
        index=False,
    )

    return summary


def compare_cox_models(
    primary: CoxPHFitter,
    sensitivity: CoxPHFitter,
) -> None:
    """Compare common hazard-ratio estimates across both models."""
    left = primary.summary.reset_index()
    left = left.rename(
        columns={
            left.columns[0]: "term",
            "exp(coef)": "primary_hr",
            "exp(coef) lower 95%": "primary_hr_lower_95",
            "exp(coef) upper 95%": "primary_hr_upper_95",
        }
    )
    right = sensitivity.summary.reset_index()
    right = right.rename(
        columns={
            right.columns[0]: "term",
            "exp(coef)": "stratified_hr",
            "exp(coef) lower 95%": "stratified_hr_lower_95",
            "exp(coef) upper 95%": "stratified_hr_upper_95",
        }
    )

    left = left[
        [
            "term",
            "primary_hr",
            "primary_hr_lower_95",
            "primary_hr_upper_95",
        ]
    ]
    right = right[
        [
            "term",
            "stratified_hr",
            "stratified_hr_lower_95",
            "stratified_hr_upper_95",
        ]
    ]

    comparison = left.merge(
        right,
        on="term",
        how="outer",
        validate="one_to_one",
    )
    comparison["relative_hr_change_percent"] = (
        100
        * (
            comparison["stratified_hr"]
            - comparison["primary_hr"]
        )
        / comparison["primary_hr"]
    )
    comparison.to_csv(
        REPORT_DIR
        / "cox_primary_vs_stratified_sensitivity.csv",
        index=False,
    )


# =============================================================================
# MANIFEST AND COMMIT-READINESS CHECKLIST
# =============================================================================


def write_run_manifest(
    survival_df: pd.DataFrame,
    primary_df: pd.DataFrame,
    sensitivity_df: pd.DataFrame,
    selected_times: list[int],
) -> None:
    """Write a reproducible manifest without any local absolute path."""
    manifest = pd.DataFrame(
        [
            {
                "setting": "script_version",
                "value": SCRIPT_VERSION,
            },
            {
                "setting": "run_timestamp_utc",
                "value": datetime.now(
                    timezone.utc
                ).isoformat(),
            },
            {
                "setting": "script_file",
                "value": project_relative_path(
                    Path(__file__)
                ),
            },
            {
                "setting": "script_sha256",
                "value": sha256_file(Path(__file__)),
            },
            {
                "setting": "data_file",
                "value": project_relative_path(
                    DATA_FILE
                ),
            },
            {
                "setting": "data_sha256",
                "value": sha256_file(DATA_FILE),
            },
            {
                "setting": "quality_filter",
                "value": (
                    f"{QUALITY_STATUS_COL} "
                    f"== {VALID_QUALITY_VALUE!r}"
                ),
            },
            {
                "setting": "duration_column",
                "value": DURATION_COL,
            },
            {
                "setting": "event_column",
                "value": EVENT_COL,
            },
            {
                "setting": "stage_column",
                "value": STAGE_COL,
            },
            {
                "setting": "selected_times_months",
                "value": json_text(selected_times),
            },
            {
                "setting": "at_risk_count_convention",
                "value": "end_of_period",
            },
            {
                "setting": "primary_numeric_covariates",
                "value": json_text(
                    COX_NUMERIC_COLS
                ),
            },
            {
                "setting": "primary_categorical_covariates",
                "value": json_text(
                    COX_CATEGORICAL_COLS
                ),
            },
            {
                "setting": "explicit_reference_categories",
                "value": json_text(
                    REFERENCE_CATEGORIES
                ),
            },
            {
                "setting": "sensitivity_strata",
                "value": json_text(
                    SENSITIVITY_STRATA_COLS
                ),
            },
            {
                "setting": "cox_penalizer",
                "value": COX_PENALIZER,
            },
            {
                "setting": "core_survival_n",
                "value": int(len(survival_df)),
            },
            {
                "setting": "primary_cox_n",
                "value": int(len(primary_df)),
            },
            {
                "setting": "stratified_cox_n",
                "value": int(len(sensitivity_df)),
            },
            {
                "setting": "python_version",
                "value": platform.python_version(),
            },
            {
                "setting": "pandas_version",
                "value": pd.__version__,
            },
            {
                "setting": "lifelines_version",
                "value": lifelines.__version__,
            },
            {
                "setting": "statsmodels_version",
                "value": statsmodels.__version__,
            },
        ]
    )
    manifest.to_csv(
        REPORT_DIR
        / "survival_analysis_run_manifest.csv",
        index=False,
    )


def file_is_nonempty(path: Path) -> bool:
    """Return True only for an existing, non-empty output file."""
    return path.exists() and path.is_file() and path.stat().st_size > 0


def write_commit_readiness_checklist(
    primary_ph: pd.DataFrame,
    stratified_ph: pd.DataFrame,
    primary_fit_warnings: pd.DataFrame,
    stratified_fit_warnings: pd.DataFrame,
) -> bool:
    """Record automated gates and manual visual-review obligations."""
    manifest_path = (
        REPORT_DIR
        / "survival_analysis_run_manifest.csv"
    )
    manifest = pd.read_csv(manifest_path)
    data_file_value = str(
        manifest.loc[
            manifest["setting"].eq("data_file"),
            "value",
        ].iloc[0]
    )
    manifest_is_relative = not Path(
        data_file_value
    ).is_absolute() and not re.match(
        r"^[A-Za-z]:[\\/]",
        data_file_value,
    )

    primary_convergence_ok = not (
        primary_fit_warnings["category"]
        .eq("ConvergenceWarning")
        .any()
        if not primary_fit_warnings.empty
        else False
    )
    stratified_convergence_ok = not (
        stratified_fit_warnings["category"]
        .eq("ConvergenceWarning")
        .any()
        if not stratified_fit_warnings.empty
        else False
    )

    primary_ph_ok = not bool(
        primary_ph["reject_ph_after_holm"].any()
    )
    stratified_ph_ok = not bool(
        stratified_ph["reject_ph_after_holm"].any()
    )

    automated_rows = [
        {
            "condition": "explicit_quality_filter",
            "status": "PASS",
            "evidence": "quality_filter_summary.csv",
        },
        {
            "condition": "manifest_has_no_local_absolute_path",
            "status": (
                "PASS"
                if manifest_is_relative
                else "FAIL"
            ),
            "evidence": data_file_value,
        },
        {
            "condition": "explicit_IIA_and_Grade_II_references",
            "status": (
                "PASS"
                if REFERENCE_CATEGORIES
                == {
                    STAGE_COL: "IIA",
                    GRADE_COL: (
                        "Moderately differentiated; Grade II"
                    ),
                }
                else "FAIL"
            ),
            "evidence": json_text(
                REFERENCE_CATEGORIES
            ),
        },
        {
            "condition": "counts_and_events_by_modality_available",
            "status": (
                "PASS"
                if file_is_nonempty(
                    REPORT_DIR
                    / "cox_primary_categorical_level_diagnostics.csv"
                )
                and file_is_nonempty(
                    REPORT_DIR
                    / "cox_stratified_categorical_level_diagnostics.csv"
                )
                and file_is_nonempty(
                    REPORT_DIR
                    / "cox_stratified_combined_strata_diagnostics.csv"
                )
                else "FAIL"
            ),
            "evidence": "Cox level and combined-strata diagnostics",
        },
        {
            "condition": "primary_model_convergence",
            "status": (
                "PASS"
                if primary_convergence_ok
                else "FAIL"
            ),
            "evidence": "cox_primary_fit_warnings.csv",
        },
        {
            "condition": "stratified_model_convergence",
            "status": (
                "PASS"
                if stratified_convergence_ok
                else "FAIL"
            ),
            "evidence": "cox_stratified_fit_warnings.csv",
        },
        {
            "condition": "primary_model_PH_after_Holm",
            "status": (
                "PASS"
                if primary_ph_ok
                else "FAIL"
            ),
            "evidence": "cox_primary_proportional_hazards_test.csv",
        },
        {
            "condition": "stratified_model_PH_after_Holm",
            "status": (
                "PASS"
                if stratified_ph_ok
                else "FAIL"
            ),
            "evidence": "cox_stratified_proportional_hazards_test.csv",
        },
        {
            "condition": "check_assumptions_reports_generated",
            "status": (
                "PASS"
                if file_is_nonempty(
                    REPORT_DIR
                    / "cox_primary_check_assumptions_report.txt"
                )
                and file_is_nonempty(
                    REPORT_DIR
                    / "cox_stratified_check_assumptions_report.txt"
                )
                else "FAIL"
            ),
            "evidence": "primary and stratified text reports",
        },
        {
            "condition": "Schoenfeld_graphs_visually_examined",
            "status": "MANUAL_REVIEW_REQUIRED",
            "evidence": (
                "Review all files listed in "
                "cox_*_schoenfeld_figure_index.csv"
            ),
        },
        {
            "condition": "Kaplan_Meier_and_risk_tables_visually_examined",
            "status": "MANUAL_REVIEW_REQUIRED",
            "evidence": (
                "Review both Kaplan–Meier PNG files and "
                "at_risk_counts_selected_times.csv"
            ),
        },
    ]

    checklist = pd.DataFrame(automated_rows)
    automated_pass = bool(
        checklist.loc[
            checklist["status"].isin(
                ["PASS", "FAIL"]
            ),
            "status",
        ].eq("PASS").all()
    )
    checklist = pd.concat(
        [
            checklist,
            pd.DataFrame(
                [
                    {
                        "condition": "automated_commit_gate",
                        "status": (
                            "PASS"
                            if automated_pass
                            else "FAIL"
                        ),
                        "evidence": (
                            "Manual visual reviews remain mandatory."
                        ),
                    }
                ]
            ),
        ],
        ignore_index=True,
    )
    checklist.to_csv(
        REPORT_DIR / "commit_readiness_checklist.csv",
        index=False,
    )
    return automated_pass


# =============================================================================
# MAIN
# =============================================================================


def main() -> None:
    """Run the complete, reproducible survival-analysis workflow."""
    clean_previous_outputs()

    print(f"Project root: {PROJECT_ROOT}")
    print(f"Reading data: {DATA_FILE}")

    raw = load_dataset(DATA_FILE)
    validate_required_schema(raw)
    validate_case_ids(raw)

    quality_valid, quality_excluded_n = (
        filter_valid_quality_records(raw)
    )

    # Domain labels are checked after the explicit quality filter so that
    # records already classified as non-valid do not block the analysis.
    validate_expected_categories(
        quality_valid,
        STAGE_COL,
        STAGE_ORDER,
    )
    validate_expected_categories(
        quality_valid,
        GRADE_COL,
        EXPECTED_GRADE_VALUES,
    )
    validate_expected_categories(
        quality_valid,
        "estrogen_status",
        EXPECTED_RECEPTOR_VALUES,
    )
    validate_expected_categories(
        quality_valid,
        "progesterone_status",
        EXPECTED_RECEPTOR_VALUES,
    )

    quality_valid = validate_event_indicator(
        quality_valid
    )

    (
        survival_df,
        core_exclusion_report,
        core_excluded_n,
    ) = prepare_survival_data(quality_valid)

    write_survival_flow_reports(
        source_n=int(len(raw)),
        quality_valid_n=int(len(quality_valid)),
        quality_excluded_n=quality_excluded_n,
        core_survival_df=survival_df,
        core_excluded_n=core_excluded_n,
        core_report=core_exclusion_report,
    )

    times = selected_times_within_followup(
        survival_df
    )
    save_event_and_censor_summaries(
        survival_df
    )
    create_at_risk_table(
        survival_df,
        times,
    )
    plot_kaplan_meier(
        survival_df,
        times,
    )
    run_logrank_tests(
        survival_df
    )

    primary_df, _, _ = prepare_cox_dataset(
        survival_df,
        prefix="cox_primary",
    )
    primary, primary_warnings = fit_cox_model(
        primary_df,
        prefix="cox_primary",
        title="Primary Cox model: adjusted hazard ratios",
    )
    primary_ph = check_proportional_hazards(
        primary,
        primary_df,
        prefix="cox_primary",
    )

    sensitivity_df, _, _ = prepare_cox_dataset(
        survival_df,
        prefix="cox_stratified",
        strata_cols=SENSITIVITY_STRATA_COLS,
    )
    sensitivity, stratified_warnings = fit_cox_model(
        sensitivity_df,
        prefix="cox_stratified",
        title=(
            "Sensitivity Cox model stratified "
            "by ER and PR status"
        ),
        strata_cols=SENSITIVITY_STRATA_COLS,
    )
    stratified_ph = check_proportional_hazards(
        sensitivity,
        sensitivity_df,
        prefix="cox_stratified",
    )

    compare_cox_models(
        primary,
        sensitivity,
    )
    write_run_manifest(
        survival_df,
        primary_df,
        sensitivity_df,
        times,
    )
    automated_gate = write_commit_readiness_checklist(
        primary_ph,
        stratified_ph,
        primary_warnings,
        stratified_warnings,
    )

    print("\nAnalysis completed.")
    print("Primary model: age + overall_stage + grade")
    print(
        "Sensitivity model: same covariates, "
        "stratified by ER and PR status"
    )
    print(
        "Automated commit gate: "
        + ("PASS" if automated_gate else "FAIL")
    )
    print(
        "Manual review remains required for the new "
        "Schoenfeld and Kaplan–Meier figures."
    )
    print(f"Figures: {FIGURE_DIR}")
    print(f"Reports: {REPORT_DIR}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nAnalysis interrupted by the user.")
        sys.exit(130)
